[package]
name = "metahash"
version = "0.1.0"
edition = "2024"

[dependencies]
twox-hash           = { version = "2.1.2", default-features = false, features = [ "std", "random", "xxhash3_128" ] }
clap = { version = "4.5.1", features = ["derive"] }
anyhow = "1.0.79"
filetime = "0.2.23"
hashbrown           = { version = "0.16.0", features = [ "serde" ] }
foldhash            = "0.2.0"
parking_lot         = "0.12.5"
percent-encoding    = "2.3.2"
memchr              = "2.7.6"
soft-canonicalize   = { version = "0.4.5", features = ["dunce"] }

